version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "development"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/docs-site"
    target-branch: "development"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
