package io.testfly.junit5;

import io.testfly.ai.AiFailureAnalyzer;
import io.testfly.performance.PerformanceCollector;
import io.testfly.quarantine.QuarantineLoader;
import io.testfly.api.TestFlyApi;
import io.testfly.browser.BrowserContext;
import io.testfly.browser.ConsoleErrorCollector;
import io.testfly.client.ApiClient;
import io.testfly.clock.TestClock;
import io.testfly.config.TestFlyConfig;
import io.testfly.context.ScenarioContext;
import io.testfly.db.DbConnectionFactory;
import io.testfly.driver.DriverManager;
import io.testfly.healing.HealLog;
import io.testfly.hooks.HookRegistry;
import io.testfly.internal.TestFlyContext;
import io.testfly.lifecycle.FrameworkBootstrap;
import io.testfly.metrics.ExecutionMetrics;
import io.testfly.network.NetworkMock;
import io.testfly.recording.RecordingManager;
import io.testfly.reporting.ScreenshotManager;
import io.testfly.session.MultiSessionManager;
import io.testfly.steps.StepLogger;
import io.testfly.steps.StepStatus;
import io.testfly.testdata.TestDataStore;
import io.testfly.listeners.Retryable;
import io.testfly.email.MailboxClient;
import io.testfly.precondition.PreConditionRegistry;
import io.testfly.precondition.PreConditionRunner;
import io.testfly.test.NoBrowser;
import io.testfly.testmanagement.TestManagementReporter;
import io.testfly.tracing.TraceRecorder;
import org.junit.jupiter.api.extension.AfterAllCallback;
import org.junit.jupiter.api.extension.AfterEachCallback;
import org.junit.jupiter.api.extension.BeforeAllCallback;
import org.junit.jupiter.api.extension.BeforeEachCallback;
import org.junit.jupiter.api.extension.ExtensionContext;
import org.junit.jupiter.api.extension.InvocationInterceptor;
import org.junit.jupiter.api.extension.ParameterContext;
import org.junit.jupiter.api.extension.ParameterResolver;
import org.junit.jupiter.api.extension.ReflectiveInvocationContext;
import org.openqa.selenium.WebDriver;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.List;
import java.util.Optional;

/**
 * JUnit 5 extension providing the full TestFly lifecycle.
 *
 * <p>Equivalent to {@code SuiteExecutionListener + TestExecutionListener} in TestNG.
 * Register via {@link EnableTestFly} or directly:
 * <pre>
 * {@literal @}ExtendWith(TestFlyExtension.class)
 * class LoginTest {
 *
 *     {@literal @}Test
 *     void validLogin(WebDriver driver) {   // parameter injection
 *         driver.get("https://example.com");
 *     }
 * }
 * </pre>
 *
 * <p>Lifecycle per test method:
 * <ol>
 *   <li>{@code beforeAll}  — bootstrap framework once per class (idempotent)</li>
 *   <li>{@code beforeEach} — create driver, start timing, notify hooks</li>
 *   <li>Test method executes (WebDriver injectable as parameter)</li>
 *   <li>{@code afterEach}  — screenshot on failure, record status, quit driver, cleanup</li>
 *   <li>{@code afterAll}   — quit per-suite driver when lifecycle=per-suite</li>
 * </ol>
 *
 * <p>Suite-level HTML report is generated by {@link TestFlyLauncherListener},
 * registered automatically via ServiceLoader.
 */
@TestFlyApi(since = "1.9.0")
public class TestFlyExtension
        implements BeforeAllCallback, AfterAllCallback,
                   BeforeEachCallback, AfterEachCallback,
                   ParameterResolver, InvocationInterceptor {

    private final ReportPortalJUnit5Bridge rpBridge = new ReportPortalJUnit5Bridge();

    @Override
    public void beforeAll(ExtensionContext context) {
        FrameworkBootstrap.initialize();
        PreConditionRegistry.loadAll();
        TestManagementReporter.getInstance().onSuiteStart();

        // Delegate to ReportPortal extension — it reads rp.* system properties
        // (set by FrameworkBootstrap) and creates the launch.
        if (rpBridge.isAvailable()) {
            rpBridge.beforeAll(context);
        }
    }

    @Override
    public void beforeEach(ExtensionContext context) {
        String testId = testId(context);
        TestFlyContext.setCurrentTestId(testId);
        ExecutionMetrics.clearSteps(testId);
        ExecutionMetrics.markStart(testId);
        ExecutionMetrics.recordTestClass(testId, context.getRequiredTestClass().getSimpleName());
        ExecutionMetrics.recordDescription(testId, context.getDisplayName());

        // Quarantine check — abort before any resource is allocated
        checkQuarantine(context);

        boolean noBrowser = skipBrowser(context);
        if (!noBrowser) {
            DriverManager.createDriver();
            String sessionUrl = DriverManager.getCloudSessionUrl();
            if (sessionUrl != null) ExecutionMetrics.recordSessionUrl(testId, sessionUrl);

            // Run @PreCondition if present on method or class (first attempt — not a retry)
            PreConditionRunner.run(context.getRequiredTestMethod(), false);

            TestFlyConfig.Recording rec = TestFlyContext.getConfig().getRecording();
            if (rec != null && rec.isEnabled()) {
                RecordingManager.start(DriverManager.getDriver(), rec.getFps(), rec.getMaxDurationSeconds());
            }

            if (ConsoleErrorCollector.isEnabled()) {
                ConsoleErrorCollector.injectShim();
            }
        }

        autoClearEmailIfEnabled();
        HookRegistry.onTestStart(testId);

        // ReportPortal: start test item
        if (rpBridge.isAvailable()) {
            rpBridge.beforeEach(context);
        }
    }

    @Override
    public void afterEach(ExtensionContext context) {
        String testId   = TestFlyContext.getCurrentTestId();
        String testName = context.getRequiredTestMethod().getName();
        Optional<Throwable> failure = context.getExecutionException();

        boolean noBrowser = skipBrowser(context);
        try {
            if (failure.isPresent()) {
                Throwable cause = failure.get();

                if (!noBrowser && ConsoleErrorCollector.isEnabled()) {
                    List<String> errors = ConsoleErrorCollector.collect();
                    errors.forEach(e -> StepLogger.step("[JS Error] " + e, StepStatus.WARN));
                }

                String screenshotPath = noBrowser ? null : ScreenshotManager.capture(testName);
                ExecutionMetrics.recordScreenshot(testId, screenshotPath);
                ExecutionMetrics.recordError(testId, cause);
                ExecutionMetrics.recordStatus(testId, "FAILED");
                ExecutionMetrics.markEnd(testId);

                if (!noBrowser) {
                    saveTraceIfEnabled(testId, testName, false);
                    RecordingManager.saveOnFailure(testId);
                }
                runAiAnalysisIfEnabled(testId);
                HookRegistry.onTestFailure(testId, cause);
                TestManagementReporter.getInstance().onTestResult(
                        context.getRequiredTestMethod(), "FAILED",
                        cause.getMessage());

                // ReportPortal: report test failure
                if (rpBridge.isAvailable()) {
                    rpBridge.testFailed(context, cause);
                }

            } else {
                if (!noBrowser && ConsoleErrorCollector.isEnabled()) {
                    List<String> errors = ConsoleErrorCollector.collect();
                    errors.forEach(e -> StepLogger.step("[JS Error] " + e, StepStatus.WARN));

                    boolean failOnErrors = TestFlyContext.getConfig().getBrowser() != null
                            && TestFlyContext.getConfig().getBrowser().isFailOnConsoleErrors();
                    if (failOnErrors && !errors.isEmpty()) {
                        ExecutionMetrics.recordStatus(testId, "FAILED");
                        ExecutionMetrics.markEnd(testId);
                        RecordingManager.stop();
                        HookRegistry.onTestFailure(testId,
                                new AssertionError("Console errors detected: " + errors.get(0)));
                        return;
                    }
                }

                capturePerformanceIfEnabled(testId, context);
                ExecutionMetrics.recordStatus(testId, "PASSED");
                ExecutionMetrics.markEnd(testId);
                if (!noBrowser) {
                    saveTraceIfEnabled(testId, testName, true);
                    RecordingManager.stop();
                }
                HookRegistry.onTestEnd(testId, "PASSED");
                TestManagementReporter.getInstance().onTestResult(
                        context.getRequiredTestMethod(), "PASSED", null);

                // ReportPortal: report test success
                if (rpBridge.isAvailable()) {
                    rpBridge.testSuccessful(context);
                }
            }

            // ReportPortal: finish test item
            if (rpBridge.isAvailable()) {
                rpBridge.afterTestExecution(context);
            }
        } finally {
            MultiSessionManager.clearAll();
            DbConnectionFactory.closeAll();
            ScenarioContext.clear();
            TestDataStore.clear();
            ApiClient.clearGlobalAuth();
            BrowserContext.clear();
            NetworkMock.cleanup();
            TestClock.autoReset();
            if (!noBrowser && DriverManager.shouldQuitAfterTest()) DriverManager.quitDriver();
            TestFlyContext.clearCurrentTestId();
        }
    }

    @Override
    public void afterAll(ExtensionContext context) {
        // ReportPortal: finish the launch
        if (rpBridge.isAvailable()) {
            rpBridge.afterAll(context);
        }

        DriverManager.quitAllSuiteDrivers();
        DriverManager.quitDriver();
        HealLog.export();
    }

    // ── Retry via InvocationInterceptor ───────────────────────────────────

    @Override
    public void interceptTestMethod(
            Invocation<Void> invocation,
            ReflectiveInvocationContext<Method> invocationContext,
            ExtensionContext context) throws Throwable {

        int maxRetries = resolveMaxRetries(context);

        if (maxRetries <= 0) {
            invocation.proceed();
            return;
        }

        String testId = testId(context);
        Throwable lastFailure = null;

        for (int attempt = 1; attempt <= maxRetries + 1; attempt++) {
            try {
                if (attempt == 1) {
                    invocation.proceed();
                } else {
                    // Record retry, recreate driver, re-invoke via reflection
                    ExecutionMetrics.recordRetry(testId);
                    ExecutionMetrics.clearSteps(testId);
                    try { DriverManager.quitDriver(); } catch (Exception ignored) {}
                    DriverManager.createDriver();

                    // Re-apply @PreCondition with isRetry=true — invalidates cache
                    // so the provider reruns rather than restoring a broken session
                    PreConditionRunner.run(invocationContext.getExecutable(), true);

                    Method m = invocationContext.getExecutable();
                    m.setAccessible(true);
                    Object[] args = invocationContext.getArguments().stream()
                            .map(a -> a instanceof WebDriver ? DriverManager.getDriver() : a)
                            .toArray();
                    try {
                        m.invoke(context.getRequiredTestInstance(), args);
                    } catch (InvocationTargetException e) {
                        throw e.getCause();
                    }
                }
                return; // attempt succeeded
            } catch (Throwable t) {
                lastFailure = t;
            }
        }
        throw lastFailure;
    }

    private int resolveMaxRetries(ExtensionContext context) {
        // 1. Method-level @Retryable
        Retryable onMethod = context.getRequiredTestMethod().getAnnotation(Retryable.class);
        if (onMethod != null) {
            return onMethod.maxAttempts() >= 0 ? onMethod.maxAttempts() : configMaxRetries();
        }
        // 2. Class-level @Retryable
        Retryable onClass = context.getRequiredTestClass().getAnnotation(Retryable.class);
        if (onClass != null) {
            return onClass.maxAttempts() >= 0 ? onClass.maxAttempts() : configMaxRetries();
        }
        // 3. Global config
        return configMaxRetries();
    }

    private int configMaxRetries() {
        try {
            TestFlyConfig.Retry retry = TestFlyContext.getConfig().getRetry();
            if (retry == null || !retry.isEnabled()) return 0;
            return Math.max(0, retry.getMaxAttempts());
        } catch (Exception e) {
            return 0;
        }
    }

    // ── Parameter injection — WebDriver as test method parameter ──────────

    @Override
    public boolean supportsParameter(ParameterContext paramCtx, ExtensionContext extCtx) {
        return WebDriver.class.isAssignableFrom(paramCtx.getParameter().getType());
    }

    @Override
    public Object resolveParameter(ParameterContext paramCtx, ExtensionContext extCtx) {
        return DriverManager.getDriver();
    }

    // ── Helpers ────────────────────────────────────────────────────────────

    static String testId(ExtensionContext context) {
        return context.getRequiredTestClass().getName()
                + "#"
                + context.getRequiredTestMethod().getName();
    }

    private void saveTraceIfEnabled(String testId, String testName, boolean isPassing) {
        try {
            TestFlyConfig.Tracing tracing = TestFlyContext.getConfig().getTracing();
            if (tracing == null || !tracing.isEnabled()) return;
            if (isPassing && !tracing.isCaptureOnPass()) return;
            TraceRecorder.save(testId, testName);
        } catch (Exception ignored) {}
    }

    private void runAiAnalysisIfEnabled(String testId) {
        try {
            String pageUrl = null, pageTitle = null;
            try {
                WebDriver d = DriverManager.getDriver();
                if (d != null) { pageUrl = d.getCurrentUrl(); pageTitle = d.getTitle(); }
            } catch (Exception ignored) {}
            AiFailureAnalyzer.analyze(testId, pageUrl, pageTitle);
        } catch (Exception ignored) {}
    }

    private static void autoClearEmailIfEnabled() {
        try {
            io.testfly.config.TestFlyConfig.Email emailCfg =
                    TestFlyContext.getConfig().getEmail();
            if (emailCfg != null && emailCfg.isAutoClear()) {
                MailboxClient.create().clear();
            }
        } catch (Exception ignored) {}
    }

    private boolean skipBrowser(ExtensionContext context) {
        Method m = context.getRequiredTestMethod();
        return m.isAnnotationPresent(NoBrowser.class) ||
               context.getRequiredTestClass().isAnnotationPresent(NoBrowser.class);
    }

    private void capturePerformanceIfEnabled(String testId, ExtensionContext context) {
        try {
            TestFlyConfig.Performance cfg = TestFlyContext.getConfig().getPerformance();
            if (cfg == null || !cfg.isCaptureOnEveryTest()) return;
            if (skipBrowser(context)) return;
            io.testfly.metrics.ExecutionMetrics.recordPerformance(
                testId, PerformanceCollector.collect());
        } catch (Exception ignored) {}
    }

    private void checkQuarantine(ExtensionContext context) {
        try {
            TestFlyConfig.Quarantine cfg = TestFlyContext.getConfig().getQuarantine();
            if (cfg != null && !cfg.isEnabled()) return;
        } catch (Exception ignored) {}

        String testId = testId(context);
        if (QuarantineLoader.isQuarantined(testId)) {
            org.junit.jupiter.api.Assumptions.abort(
                "[Quarantined] " + testId + " — " + QuarantineLoader.getReason(testId)
            );
        }
    }
}
