package io.testfly.junit5;

import io.testfly.ai.AiFailureAnalyzer;
import io.testfly.performance.PerformanceCollector;
import io.testfly.quarantine.QuarantineLoader;
import io.testfly.api.TestFlyApi;
import io.testfly.browser.BrowserContext;
import io.testfly.browser.ConsoleErrorCollector;
import io.testfly.client.ApiClient;
import io.testfly.clock.TestClock;
import io.testfly.config.TestFlyConfig;
import io.testfly.context.ScenarioContext;
import io.testfly.db.DbConnectionFactory;
import io.testfly.driver.DriverManager;
import io.testfly.healing.HealLog;
import io.testfly.hooks.HookRegistry;
import io.testfly.internal.TestFlyContext;
import io.testfly.lifecycle.FrameworkBootstrap;
import io.testfly.metrics.ExecutionMetrics;
import io.testfly.network.NetworkMock;
import io.testfly.recording.RecordingManager;
import io.testfly.reporting.ScreenshotManager;
import io.testfly.session.MultiSessionManager;
import io.testfly.steps.StepLogger;
import io.testfly.steps.StepStatus;
import io.testfly.testdata.TestDataStore;
import io.testfly.listeners.Retryable;
import io.testfly.email.MailboxClient;
import io.testfly.precondition.PreConditionRegistry;
import io.testfly.precondition.PreConditionRunner;
import io.testfly.test.NoBrowser;
import io.testfly.testmanagement.TestManagementReporter;
import io.testfly.tracing.TraceRecorder;
import io.testfly.assertion.SoftAssertionCollector;
import io.testfly.assertion.SoftAssertions;
import io.testfly.client.ApiAuth;
import io.testfly.client.UseAuth;
import org.junit.jupiter.api.extension.AfterAllCallback;
import org.junit.jupiter.api.extension.AfterEachCallback;
import org.junit.jupiter.api.extension.BeforeAllCallback;
import org.junit.jupiter.api.extension.BeforeEachCallback;
import org.junit.jupiter.api.extension.ExtensionContext;
import org.junit.jupiter.api.extension.InvocationInterceptor;
import org.junit.jupiter.api.extension.ParameterContext;
import org.junit.jupiter.api.extension.ParameterResolver;
import org.junit.jupiter.api.extension.ReflectiveInvocationContext;
import org.junit.jupiter.api.extension.TestWatcher;
import org.openqa.selenium.WebDriver;

import java.lang.reflect.Method;
import java.util.List;
import java.util.Optional;

/**
 * JUnit 5 extension providing the full TestFly lifecycle.
 *
 * <p>
 * Equivalent to {@code SuiteExecutionListener + TestExecutionListener} in
 * TestNG.
 * Register via {@link EnableTestFly} or directly:
 * 
 * <pre>
 * {@literal @}ExtendWith(TestFlyExtension.class)
 * class LoginTest {
 *
 *     {@literal @}Test
 *     void validLogin(WebDriver driver) {   // parameter injection
 *         driver.get("https://example.com");
 *     }
 * }
 * </pre>
 *
 * <p>
 * Lifecycle per test method:
 * <ol>
 * <li>{@code beforeAll} — bootstrap framework once per class (idempotent)</li>
 * <li>{@code beforeEach} — create driver, start timing, notify hooks</li>
 * <li>Test method executes (WebDriver injectable as parameter)</li>
 * <li>{@code afterEach} — screenshot on failure, record status, quit driver,
 * cleanup</li>
 * <li>{@code afterAll} — quit per-suite driver when lifecycle=per-suite</li>
 * </ol>
 *
 * <p>
 * Suite-level HTML report is generated by {@link TestFlyLauncherListener},
 * registered automatically via ServiceLoader.
 */
@TestFlyApi(since = "1.9.0")
public class TestFlyExtension
        implements BeforeAllCallback, AfterAllCallback,
        BeforeEachCallback, AfterEachCallback,
        ParameterResolver, InvocationInterceptor, TestWatcher {

    private ReportPortalJUnit5Bridge rpBridge;

    @Override
    public void beforeAll(ExtensionContext context) {
        FrameworkBootstrap.initialize();
        PreConditionRegistry.loadAll();
        TestManagementReporter.getInstance().onSuiteStart();

        // Create RP bridge AFTER FrameworkBootstrap.initialize() so that
        // rp.* system properties are set before the RP agent is constructed.
        rpBridge = new ReportPortalJUnit5Bridge();

        // Delegate to ReportPortal extension — it reads rp.* system properties
        // (set by FrameworkBootstrap) and creates the launch.
        if (rpBridge.isAvailable()) {
            rpBridge.beforeAll(context);
        }
    }

    @Override
    public void beforeEach(ExtensionContext context) {
        String testId = testId(context);
        TestFlyContext.setCurrentTestId(testId);
        TestFlyContext.setCurrentTest(context.getRequiredTestClass(), context.getRequiredTestMethod());
        ExecutionMetrics.clearSteps(testId);
        ExecutionMetrics.markStart(testId);
        ExecutionMetrics.recordTestClass(testId, context.getRequiredTestClass().getSimpleName());
        ExecutionMetrics.recordDescription(testId, context.getDisplayName());

        // Quarantine check — abort before any resource is allocated
        checkQuarantine(context);

        boolean noBrowser = skipBrowser(context);
        if (!noBrowser) {
            DriverManager.createDriver();
            String sessionUrl = DriverManager.getCloudSessionUrl();
            if (sessionUrl != null)
                ExecutionMetrics.recordSessionUrl(testId, sessionUrl);

            // Run @PreCondition if present on method or class (first attempt — not a retry)
            PreConditionRunner.run(context.getRequiredTestMethod(), false);

            TestFlyConfig.Recording rec = TestFlyContext.getConfig().getRecording();
            if (rec != null && rec.isEnabled()) {
                RecordingManager.start(DriverManager.getDriver(), rec.getFps(), rec.getMaxDurationSeconds());
            }

            if (ConsoleErrorCollector.isEnabled()) {
                ConsoleErrorCollector.injectShim();
            }
        }

        autoClearEmailIfEnabled();
        applyUseAuth(context);
        loadTestData(context);
        HookRegistry.onTestStart(testId);

        // ReportPortal: start test item
        if (isRpAvailable()) {
            rpBridge.beforeEach(context);
        }
    }

    @Override
    public void testDisabled(ExtensionContext context, Optional<String> reason) {
        String testId = testId(context);
        ExecutionMetrics.markStart(testId);
        ExecutionMetrics.recordTestClass(testId, context.getRequiredTestClass().getSimpleName());
        ExecutionMetrics.recordDescription(testId, context.getDisplayName());
        ExecutionMetrics.recordStatus(testId, "SKIPPED");
        ExecutionMetrics.markEnd(testId);
        HookRegistry.onTestEnd(testId, "SKIPPED");
        TestManagementReporter.getInstance().onTestResult(
                context.getRequiredTestMethod(), "SKIPPED", reason.orElse(null));
        if (isRpAvailable()) {
            rpBridge.testDisabled(context, reason);
        }
    }

    @Override
    public void afterEach(ExtensionContext context) {
        String testId = TestFlyContext.getCurrentTestId();
        String testName = context.getRequiredTestMethod().getName();
        Optional<Throwable> failure = context.getExecutionException();

        boolean noBrowser = skipBrowser(context);
        try {
            if (failure.isPresent()) {
                Throwable cause = failure.get();

                if (cause instanceof org.opentest4j.TestAbortedException) {
                    ExecutionMetrics.recordStatus(testId, "SKIPPED");
                    ExecutionMetrics.markEnd(testId);
                    if (!noBrowser) {
                        RecordingManager.stop();
                    }
                    HookRegistry.onTestEnd(testId, "SKIPPED");
                    TestManagementReporter.getInstance().onTestResult(
                            context.getRequiredTestMethod(), "SKIPPED", cause.getMessage());
                    if (isRpAvailable()) {
                        rpBridge.testDisabled(context, Optional.ofNullable(cause.getMessage()));
                    }
                    return;
                }

                SoftAssertionCollector softCollector = SoftAssertions.get();
                if (softCollector.hasFailed()) {
                    softCollector.getFailures().forEach(e -> StepLogger.step("[Soft Assertion Failed] " + e, StepStatus.FAIL));
                }

                if (!noBrowser && ConsoleErrorCollector.isEnabled()) {
                    List<String> errors = ConsoleErrorCollector.collect();
                    errors.forEach(e -> StepLogger.step("[JS Error] " + e, StepStatus.WARN));

                    boolean failOnErrors = TestFlyContext.getConfig().getBrowser() != null
                            && TestFlyContext.getConfig().getBrowser().isFailOnConsoleErrors();
                    if (failOnErrors && !errors.isEmpty()) {
                        String consoleErrorSummary = "JS console errors detected (" + errors.size() + "): " + errors;
                        cause.addSuppressed(new AssertionError(consoleErrorSummary));
                    }
                }

                String screenshotPath = noBrowser ? null : ScreenshotManager.capture(testName);
                ExecutionMetrics.recordScreenshot(testId, screenshotPath);
                ExecutionMetrics.recordError(testId, cause);
                ExecutionMetrics.recordStatus(testId, "FAILED");
                ExecutionMetrics.markEnd(testId);

                if (!noBrowser) {
                    saveTraceIfEnabled(testId, testName, false);
                    String recPath = RecordingManager.saveOnFailure(testId);
                    ExecutionMetrics.recordRecording(testId, recPath);
                }
                runAiAnalysisIfEnabled(testId);
                HookRegistry.onTestFailure(testId, cause);
                TestManagementReporter.getInstance().onTestResult(
                        context.getRequiredTestMethod(), "FAILED",
                        cause.getMessage());

                io.testfly.loadtest.LoadTestMetrics ltmFailed = io.testfly.loadtest.LoadTestRunner.lastMetrics();
                if (ltmFailed != null) {
                    ExecutionMetrics.recordLoadTest(testId, ltmFailed);
                    io.testfly.reporting.reportportal.ReportPortalAttachmentSender.sendLoadTestMetrics(testId, ltmFailed);
                    io.testfly.loadtest.LoadTestRunner.clearLastMetrics();
                }

                // ReportPortal: report test failure
                if (isRpAvailable()) {
                    rpBridge.testFailed(context, cause);
                }

            } else {
                if (!noBrowser && ConsoleErrorCollector.isEnabled()) {
                    List<String> errors = ConsoleErrorCollector.collect();
                    errors.forEach(e -> StepLogger.step("[JS Error] " + e, StepStatus.WARN));

                    boolean failOnErrors = TestFlyContext.getConfig().getBrowser() != null
                            && TestFlyContext.getConfig().getBrowser().isFailOnConsoleErrors();
                    if (failOnErrors && !errors.isEmpty()) {
                        ExecutionMetrics.recordStatus(testId, "FAILED");
                        ExecutionMetrics.markEnd(testId);
                        RecordingManager.stop();
                        HookRegistry.onTestFailure(testId,
                                new AssertionError("Console errors detected: " + errors.get(0)));
                        return;
                    }
                }

                // Flush soft assertions — if any failed, redirect to failure path
                SoftAssertionCollector softCollector = SoftAssertions.get();
                if (softCollector.hasFailed()) {
                    List<String> softFailures = softCollector.getFailures();
                    softFailures.forEach(msg -> StepLogger.step("[Soft Assertion Failed] " + msg, StepStatus.FAIL));
                    String screenshotPath = noBrowser ? null : ScreenshotManager.capture(testName);
                    ExecutionMetrics.recordScreenshot(testId, screenshotPath);
                    String combined = softFailures.size() + " soft assertion(s) failed:\n" +
                            String.join("\n", softFailures);
                    AssertionError softError = new AssertionError(combined);
                    ExecutionMetrics.recordError(testId, softError);
                    ExecutionMetrics.recordStatus(testId, "FAILED");
                    ExecutionMetrics.markEnd(testId);
                    if (!noBrowser) {
                        saveTraceIfEnabled(testId, testName, false);
                        String recPath = RecordingManager.saveOnFailure(testId);
                        ExecutionMetrics.recordRecording(testId, recPath);
                    }
                    runAiAnalysisIfEnabled(testId);
                    HookRegistry.onTestFailure(testId, softError);
                    TestManagementReporter.getInstance().onTestResult(
                            context.getRequiredTestMethod(), "FAILED",
                            softError.getMessage());
                    if (isRpAvailable()) {
                        rpBridge.testFailed(context, softError);
                    }
                    throw softError;
                }

                capturePerformanceIfEnabled(testId, context);
                ExecutionMetrics.recordStatus(testId, "PASSED");
                ExecutionMetrics.markEnd(testId);
                if (!noBrowser) {
                    saveTraceIfEnabled(testId, testName, true);
                    RecordingManager.stop();
                }
                HookRegistry.onTestEnd(testId, "PASSED");
                TestManagementReporter.getInstance().onTestResult(
                        context.getRequiredTestMethod(), "PASSED", null);

                io.testfly.loadtest.LoadTestMetrics ltmSuccess = io.testfly.loadtest.LoadTestRunner.lastMetrics();
                if (ltmSuccess != null) {
                    ExecutionMetrics.recordLoadTest(testId, ltmSuccess);
                    io.testfly.reporting.reportportal.ReportPortalAttachmentSender.sendLoadTestMetrics(testId, ltmSuccess);
                    io.testfly.loadtest.LoadTestRunner.clearLastMetrics();
                }

                // ReportPortal: report test success
                if (isRpAvailable()) {
                    rpBridge.testSuccessful(context);
                }
            }

            // ReportPortal: finish test item
            if (isRpAvailable()) {
                rpBridge.afterTestExecution(context);
            }
        } finally {
            SoftAssertions.clear();
            MultiSessionManager.clearAll();
            DbConnectionFactory.closeAll();
            ScenarioContext.clear();
            TestDataStore.clear();
            ApiClient.clearGlobalAuth();
            BrowserContext.clear();
            NetworkMock.cleanup();
            TestClock.autoReset();
            if (!noBrowser && DriverManager.shouldQuitAfterTest())
                DriverManager.quitDriver();
            TestFlyContext.clearCurrentTest();
        }
    }

    @Override
    public void afterAll(ExtensionContext context) {
        // ReportPortal: finish the launch
        if (isRpAvailable()) {
            rpBridge.afterAll(context);
        }

        DriverManager.quitAllSuiteDrivers();
        DriverManager.quitDriver();
        HealLog.export();
    }

    // ── Retry via InvocationInterceptor ───────────────────────────────────

    @Override
    public void interceptTestMethod(
            Invocation<Void> invocation,
            ReflectiveInvocationContext<Method> invocationContext,
            ExtensionContext context) throws Throwable {

        int maxRetries = resolveMaxRetries(context);

        if (maxRetries <= 0) {
            invocation.proceed();
            return;
        }

        String testId = testId(context);
        Throwable lastFailure = null;

        for (int attempt = 1; attempt <= maxRetries + 1; attempt++) {
            try {
                if (attempt == 1) {
                    invocation.proceed();
                } else {
                    // Record retry, recreate driver, re-invoke via reflection
                    ExecutionMetrics.recordRetry(testId);
                    ExecutionMetrics.clearSteps(testId);
                    try {
                        DriverManager.quitDriver();
                    } catch (Exception ignored) {
                    }
                    DriverManager.createDriver();

                    // Re-apply @PreCondition with isRetry=true — invalidates cache
                    // so the provider reruns rather than restoring a broken session
                    PreConditionRunner.run(invocationContext.getExecutable(), true);

                    // Retry via the invocation context target — uses the same
                    // instance the interceptor chain resolved, not a separate
                    // lookup that could bypass other extensions' state.
                    Method m = invocationContext.getExecutable();
                    m.setAccessible(true);
                    Object target = invocationContext.getTarget().orElse(null);
                    Object[] args = invocationContext.getArguments().stream()
                            .map(a -> a instanceof WebDriver ? DriverManager.getDriver() : a)
                            .toArray();
                    try {
                        m.invoke(target, args);
                    } catch (java.lang.reflect.InvocationTargetException e) {
                        throw e.getCause();
                    }
                }
                return; // attempt succeeded
            } catch (Throwable t) {
                lastFailure = t;
            }
        }
        if (lastFailure != null) {
            throw lastFailure;
        }
    }

    private int resolveMaxRetries(ExtensionContext context) {
        // 1. Method-level @Retryable
        Retryable onMethod = context.getRequiredTestMethod().getAnnotation(Retryable.class);
        if (onMethod != null) {
            return onMethod.maxAttempts() >= 0 ? onMethod.maxAttempts() : configMaxRetries();
        }
        // 2. Class-level @Retryable
        Retryable onClass = context.getRequiredTestClass().getAnnotation(Retryable.class);
        if (onClass != null) {
            return onClass.maxAttempts() >= 0 ? onClass.maxAttempts() : configMaxRetries();
        }
        // 3. Global config
        return configMaxRetries();
    }

    private int configMaxRetries() {
        try {
            TestFlyConfig.Retry retry = TestFlyContext.getConfig().getRetry();
            if (retry == null || !retry.isEnabled())
                return 0;
            return Math.max(0, retry.getMaxAttempts());
        } catch (Exception e) {
            return 0;
        }
    }

    // ── Parameter injection — WebDriver as test method parameter ──────────

    @Override
    public boolean supportsParameter(ParameterContext paramCtx, ExtensionContext extCtx) {
        return WebDriver.class.isAssignableFrom(paramCtx.getParameter().getType());
    }

    @Override
    public Object resolveParameter(ParameterContext paramCtx, ExtensionContext extCtx) {
        return DriverManager.getDriver();
    }

    // ── Helpers ────────────────────────────────────────────────────────────

    private boolean isRpAvailable() {
        return rpBridge != null && rpBridge.isAvailable();
    }

    static String testId(ExtensionContext context) {
        return context.getRequiredTestClass().getName()
                + "#"
                + context.getRequiredTestMethod().getName();
    }

    private void saveTraceIfEnabled(String testId, String testName, boolean isPassing) {
        try {
            TestFlyConfig.Tracing tracing = TestFlyContext.getConfig().getTracing();
            if (tracing == null || !tracing.isEnabled())
                return;
            if (isPassing && !tracing.isCaptureOnPass())
                return;
            TraceRecorder.save(testId, testName);
        } catch (Exception ignored) {
        }
    }

    private void runAiAnalysisIfEnabled(String testId) {
        try {
            String pageUrl = null, pageTitle = null;
            try {
                WebDriver d = DriverManager.getDriver();
                if (d != null) {
                    pageUrl = d.getCurrentUrl();
                    pageTitle = d.getTitle();
                }
            } catch (Exception ignored) {
            }
            AiFailureAnalyzer.analyze(testId, pageUrl, pageTitle);
        } catch (Exception ignored) {
        }
    }

    private static void autoClearEmailIfEnabled() {
        try {
            io.testfly.config.TestFlyConfig.Email emailCfg = TestFlyContext.getConfig().getEmail();
            if (emailCfg != null && emailCfg.isAutoClear()) {
                MailboxClient.create().clear();
            }
        } catch (Exception ignored) {
        }
    }

    private boolean skipBrowser(ExtensionContext context) {
        Class<?> clazz = context.getRequiredTestClass();
        Method m = context.getRequiredTestMethod();
        if (io.testfly.test.BaseApiTest.class.isAssignableFrom(clazz) ||
                BaseJUnit5ApiTest.class.isAssignableFrom(clazz)) {
            return true;
        }
        if (io.testfly.loadtest.BaseLoadTest.class.isAssignableFrom(clazz) ||
                io.testfly.test.support.LoadTestSupport.class.isAssignableFrom(clazz) ||
                clazz.isAnnotationPresent(io.testfly.loadtest.LoadTest.class) ||
                m.isAnnotationPresent(io.testfly.loadtest.LoadTest.class) ||
                clazz.getName().toLowerCase().contains("loadtest")) {
            return true;
        }
        return m.isAnnotationPresent(NoBrowser.class) ||
                clazz.isAnnotationPresent(NoBrowser.class);
    }

    private void applyUseAuth(ExtensionContext context) {
        UseAuth annotation = context.getRequiredTestMethod().getAnnotation(UseAuth.class);
        if (annotation == null) {
            annotation = context.getRequiredTestClass().getAnnotation(UseAuth.class);
        }
        if (annotation == null)
            return;

        String strategyName = annotation.value();
        try {
            TestFlyConfig.Api api = TestFlyContext.getConfig().getApi();
            if (api == null || api.getAuth() == null)
                return;
            TestFlyConfig.Api.AuthStrategy strategy = api.getAuth().get(strategyName);
            if (strategy == null) {
                throw new IllegalStateException(
                        "[UseAuth] No auth strategy named '" + strategyName + "' found in api.auth config");
            }
            ApiAuth auth = resolveAuthStrategy(strategy);
            if (auth != null)
                ApiClient.setGlobalAuth(auth);
        } catch (IllegalStateException e) {
            throw e;
        } catch (Exception e) {
            throw new RuntimeException("[UseAuth] Failed to apply auth strategy '" + strategyName + "'", e);
        }
    }

    private ApiAuth resolveAuthStrategy(TestFlyConfig.Api.AuthStrategy s) {
        String type = s.getType();
        if (type == null)
            return null;
        return switch (type.toLowerCase()) {
            case "bearer" -> ApiAuth.bearerToken(resolveEnvVar(s.getToken()));
            case "basic" -> ApiAuth.basicAuth(resolveEnvVar(s.getUsername()), resolveEnvVar(s.getPassword()));
            case "oauth2" -> ApiAuth.oauth2(resolveEnvVar(s.getTokenUrl()),
                    resolveEnvVar(s.getClientId()),
                    resolveEnvVar(s.getClientSecret()));
            case "apikey", "api_key", "apikey-header" -> ApiAuth.apiKey(
                    s.getHeaderName() != null ? s.getHeaderName() : "X-Api-Key",
                    resolveEnvVar(s.getApiKey() != null ? s.getApiKey() : s.getToken()));
            case "apikey-query", "api_key_query" -> ApiAuth.apiKeyQuery(
                    s.getHeaderName() != null ? s.getHeaderName() : "api_key",
                    resolveEnvVar(s.getApiKey() != null ? s.getApiKey() : s.getToken()));
            case "digest" -> ApiAuth.digest(resolveEnvVar(s.getUsername()), resolveEnvVar(s.getPassword()));
            case "hmac" -> ApiAuth.hmac(resolveEnvVar(s.getApiKey()), resolveEnvVar(s.getSecret()), s.getAlgorithm());
            case "oauth2_password", "oauth2-password", "password" -> ApiAuth.oauth2Password(
                    resolveEnvVar(s.getTokenUrl()), resolveEnvVar(s.getClientId()),
                    resolveEnvVar(s.getClientSecret()), resolveEnvVar(s.getUsername()), resolveEnvVar(s.getPassword()));
            default -> throw new IllegalArgumentException(
                    "[UseAuth] Unknown auth type: '" + type
                            + "'. Use bearer, basic, oauth2, apiKey, digest, hmac, oauth2_password");
        };
    }

    private String resolveEnvVar(String value) {
        if (value == null)
            return null;
        if (value.startsWith("${") && value.endsWith("}")) {
            String varName = value.substring(2, value.length() - 1);
            String resolved = System.getenv(varName);
            if (resolved == null)
                resolved = System.getProperty(varName);
            return resolved != null ? resolved : value;
        }
        return value;
    }

    private void loadTestData(ExtensionContext context) {
        io.testfly.testdata.TestData annotation = context.getRequiredTestMethod()
                .getAnnotation(io.testfly.testdata.TestData.class);
        if (annotation == null) {
            annotation = context.getRequiredTestClass()
                    .getAnnotation(io.testfly.testdata.TestData.class);
        }
        if (annotation != null) {
            io.testfly.testdata.TestDataStore.set(
                    io.testfly.testdata.TestDataLoader.load(
                            annotation.value(), annotation.sheet(), annotation.row()));
        }
    }

    private void capturePerformanceIfEnabled(String testId, ExtensionContext context) {
        try {
            TestFlyConfig.Performance cfg = TestFlyContext.getConfig().getPerformance();
            if (cfg == null || !cfg.isCaptureOnEveryTest())
                return;
            if (skipBrowser(context))
                return;
            io.testfly.metrics.ExecutionMetrics.recordPerformance(
                    testId, PerformanceCollector.collect());
        } catch (Exception ignored) {
        }
    }

    private void checkQuarantine(ExtensionContext context) {
        try {
            TestFlyConfig.Quarantine cfg = TestFlyContext.getConfig().getQuarantine();
            if (cfg != null && !cfg.isEnabled())
                return;
        } catch (Exception ignored) {
        }

        String testId = testId(context);
        if (QuarantineLoader.isQuarantined(testId)) {
            org.junit.jupiter.api.Assumptions.abort(
                    "[Quarantined] " + testId + " — " + QuarantineLoader.getReason(testId));
        }
    }
}
