package io.testfly.loadtest;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.testfly.api.TestFlyApi;
import io.testfly.reporting.HtmlReportGenerator;
import io.testfly.reporting.ReportAdapter;
import io.testfly.reporting.ReportPaths;

import java.io.File;
import java.io.FileWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;

/**
 * {@link ReportAdapter} implementation for load testing.
 *
 * <p>
 * Invoked by the TestFly reporting pipeline after suite completion.
 * Checks for recorded load-test results in {@code testfly-metrics.json},
 * correlates native Gatling simulation HTML reports, and ensures load test
 * metrics are rendered in the HTML report and standalone load test report.
 */
@TestFlyApi(since = "1.1.0")
public final class LoadTestReportAdapter implements ReportAdapter {

    @Override
    public String getName() {
        return "loadtest";
    }

    @Override
    public void generate(File metricsJson) {
        try {
            if (metricsJson == null || !metricsJson.exists() || metricsJson.length() == 0) {
                return;
            }

            ObjectMapper mapper = new ObjectMapper();
            JsonNode root = mapper.readTree(metricsJson);

            if (!root.has("loadTests") || !root.get("loadTests").isArray() || root.get("loadTests").isEmpty()) {
                return;
            }

            // Ensure main HTML report is generated for this metrics file
            HtmlReportGenerator.generate(metricsJson);

            File baseDir = metricsJson.getParentFile() != null ? metricsJson.getParentFile() : new File(ReportPaths.baseDir());

            // Check if native Gatling reports were generated and locate them
            File loadTestDir = new File(baseDir, "loadtest");
            if (!loadTestDir.exists() || !loadTestDir.isDirectory()) {
                loadTestDir = ReportPaths.loadTestDir();
            }
            if (loadTestDir.exists() && loadTestDir.isDirectory()) {
                List<File> gatlingReports = findGatlingReports(loadTestDir);
                for (File gr : gatlingReports) {
                    System.out.println("[LoadTest] 📊 Gatling HTML report: " + gr.getAbsolutePath());
                }
            }

            // Generate standalone loadtest-report.html if main report exists
            File mainReport = new File(baseDir, "testfly-report.html");
            if (!mainReport.exists()) {
                mainReport = ReportPaths.htmlReport();
            }
            if (mainReport.exists()) {
                File standaloneReport = new File(baseDir, "loadtest-report.html");
                String htmlContent = Files.readString(mainReport.toPath(), StandardCharsets.UTF_8);
                // Set default tab to loadtest in the standalone copy
                htmlContent = htmlContent.replace(
                        "let currentViewMode = 'cumulative';",
                        "let currentViewMode = 'cumulative'; try { localStorage.setItem('testfly-active-tab', 'loadtest'); } catch(e){}");
                try (FileWriter writer = new FileWriter(standaloneReport)) {
                    writer.write(htmlContent);
                }
                System.out.println("[LoadTest] Standalone report generated: " + standaloneReport.getPath());
            }

        } catch (Exception e) {
            // Per Acceptance Criteria: Report generation failure must NOT fail the build
            System.err.println("[LoadTest] Report generation error (non-fatal): " + e.getMessage());
        }
    }

    /**
     * Searches recursively for all {@code index.html} reports generated by Gatling.
     */
    public static List<File> findGatlingReports(File baseDir) {
        List<File> reports = new ArrayList<>();
        if (baseDir == null || !baseDir.exists() || !baseDir.isDirectory()) {
            return reports;
        }

        File[] subdirs = baseDir.listFiles(File::isDirectory);
        if (subdirs == null) {
            return reports;
        }

        // Sort descending by last modified
        Arrays.sort(subdirs, Comparator.comparingLong(File::lastModified).reversed());

        for (File dir : subdirs) {
            File[] simDirs = dir.listFiles(File::isDirectory);
            if (simDirs != null) {
                for (File simDir : simDirs) {
                    File indexFile = new File(simDir, "index.html");
                    if (indexFile.exists() && indexFile.length() > 0) {
                        reports.add(indexFile);
                    }
                }
            }
            File directIndex = new File(dir, "index.html");
            if (directIndex.exists() && directIndex.length() > 0) {
                reports.add(directIndex);
            }
        }
        return reports;
    }
}
