package io.testfly.reporting.reportportal;

import io.testfly.config.DotEnvLoader;
import io.testfly.config.TestFlyConfig;

import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Properties;

/**
 * Converts {@code reporting.reportportal} YAML configuration into the
 * property format expected by the ReportPortal TestNG agent.
 *
 * <p>The agent reads either a {@code reportportal.properties} resource on the
 * classpath or system properties prefixed with {@code rp.}. This class supports
 * both mechanisms so TestFly can inject configuration at runtime without
 * requiring consumers to maintain a separate properties file.
 *
 * <p>ReportPortal property mapping:
 * <pre>
 * endpoint    → rp.endpoint
 * apiKey      → rp.api.key
 * project     → rp.project
 * launch      → rp.launch        (enriched with run type, env, timestamp)
 * description → rp.description   (enriched with runtime context)
 * attributes  → rp.attributes
 * </pre>
 *
 * <p>Launch name format: {@code <configured-name> — <API|Web> | <env> | <timestamp>}
 * <p>Description format: multi-line with run type, base URL, user, hostname, and build info.
 */
public final class ReportPortalPropertiesWriter {

    private static final String RP_ENDPOINT    = "rp.endpoint";
    private static final String RP_API_KEY     = "rp.api.key";
    private static final String RP_PROJECT     = "rp.project";
    private static final String RP_LAUNCH      = "rp.launch";
    private static final String RP_DESCRIPTION = "rp.description";
    private static final String RP_ATTRIBUTES  = "rp.attributes";

    private static final DateTimeFormatter TIMESTAMP_FMT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

    private ReportPortalPropertiesWriter() {
        // utility class
    }

    // ── Public API ────────────────────────────────────────────────────────────

    /**
     * Builds the ReportPortal properties from the supplied configuration.
     *
     * <p>Launch name and description are automatically enriched with runtime
     * context (run type, environment, user, timestamp).
     *
     * @param config the TestFly configuration; must not be {@code null}
     * @return a mutable {@link Properties} instance containing the ReportPortal keys
     * @throws IllegalArgumentException if the ReportPortal configuration is incomplete
     */
    public static Properties toProperties(TestFlyConfig config) {
        return toProperties(config, null);
    }

    /**
     * Builds the ReportPortal properties with an explicit run type.
     *
     * @param config  the TestFly configuration
     * @param runType {@code "API"}, {@code "Web"}, or {@code null} for auto-detect
     * @return a mutable {@link Properties} instance
     */
    public static Properties toProperties(TestFlyConfig config, String runType) {
        if (config == null) {
            throw new IllegalArgumentException("TestFlyConfig is required");
        }
        TestFlyConfig.Reporting reporting = config.getReporting();
        TestFlyConfig.Reporting.ReportPortal rp = reporting != null ? reporting.getReportPortal() : null;
        if (rp == null) {
            throw new IllegalArgumentException("reporting.reportportal configuration is required");
        }
        if (!rp.isEnabled()) {
            return new Properties();
        }

        validate(rp);

        String resolvedRunType = resolveRunType(rp.getType(), runType);
        String launchName      = enrichLaunchName(rp.getLaunch(), resolvedRunType);
        String description     = enrichDescription(rp.getDescription(), resolvedRunType, config);

        Properties properties = new Properties();
        putIfNotBlank(properties, RP_ENDPOINT,    DotEnvLoader.resolve(rp.getEndpoint()));
        putIfNotBlank(properties, RP_API_KEY,     DotEnvLoader.resolve(rp.getApiKey()));
        putIfNotBlank(properties, RP_PROJECT,     rp.getProject());
        putIfNotBlank(properties, RP_LAUNCH,      launchName);
        putIfNotBlank(properties, RP_DESCRIPTION, description);
        putIfNotBlank(properties, RP_ATTRIBUTES,  rp.getAttributes());

        return properties;
    }

    /**
     * Writes the ReportPortal configuration as a properties file to the
     * requested path, then returns the absolute path of the generated file.
     *
     * @param config the TestFly configuration
     * @param target the destination file path
     * @return the written file path
     */
    public static Path writeToFile(TestFlyConfig config, Path target) {
        Properties properties = toProperties(config);
        try {
            Files.createDirectories(target.getParent());
            try (java.io.Writer writer = Files.newBufferedWriter(target)) {
                properties.store(writer, "Generated by TestFly for ReportPortal");
            }
            return target.toAbsolutePath();
        } catch (IOException e) {
            throw new UncheckedIOException("Failed to write ReportPortal properties to " + target, e);
        }
    }

    /**
     * Applies the ReportPortal configuration as system properties so the
     * ReportPortal agent can read them without a properties file.
     *
     * @param config the TestFly configuration
     */
    public static void applyAsSystemProperties(TestFlyConfig config) {
        Properties properties = toProperties(config);
        for (String name : properties.stringPropertyNames()) {
            System.setProperty(name, properties.getProperty(name));
        }
    }

    /**
     * Re-applies the ReportPortal properties with the given run type.
     * Called by SuiteExecutionListener after detecting the run type from
     * the suite's test classes — updates {@code rp.launch} and
     * {@code rp.description} before the RP agent creates the launch.
     *
     * @param config  the TestFly configuration
     * @param runType {@code "API"} or {@code "Web"}
     */
    public static void reapplyWithRunType(TestFlyConfig config, String runType) {
        Properties properties = toProperties(config, runType);
        for (String name : properties.stringPropertyNames()) {
            System.setProperty(name, properties.getProperty(name));
        }
    }

    /**
     * Returns the properties content as a single string, suitable for tests or
     * debugging. Secrets are masked.
     */
    public static String toMaskedString(TestFlyConfig config) {
        Properties properties = toProperties(config);
        Properties masked = new Properties();
        for (String name : properties.stringPropertyNames()) {
            String value = properties.getProperty(name);
            if (name.toLowerCase(java.util.Locale.ROOT).contains("key")
                    || name.toLowerCase(java.util.Locale.ROOT).contains("token")) {
                value = mask(value);
            }
            masked.setProperty(name, value);
        }
        StringWriter writer = new StringWriter();
        try {
            masked.store(writer, "Generated by TestFly for ReportPortal");
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
        return writer.toString();
    }

    public static void validate(TestFlyConfig.Reporting.ReportPortal rp) {
        if (isBlank(rp.getEndpoint())) {
            throw new IllegalArgumentException("reporting.reportportal.endpoint is required when ReportPortal is enabled");
        }
        if (isBlank(rp.getApiKey())) {
            throw new IllegalArgumentException("reporting.reportportal.apiKey is required when ReportPortal is enabled");
        }
        if (isBlank(rp.getProject())) {
            throw new IllegalArgumentException("reporting.reportportal.project is required when ReportPortal is enabled");
        }
        if (isBlank(rp.getLaunch())) {
            throw new IllegalArgumentException("reporting.reportportal.launch is required when ReportPortal is enabled");
        }
    }

    // ── Launch name enrichment ────────────────────────────────────────────────

    /**
     * Builds an enriched launch name.
     *
     * <p>Format: {@code <base-name> — <API|Web> | <env> | <timestamp>}
     * <p>Example: {@code Demo Web - Dev — API | dev | 2026-08-22 15:30}
     */
    public static String enrichLaunchName(String baseName, String runType) {
        StringBuilder sb = new StringBuilder(baseName != null ? baseName : "TestFly Suite");
        sb.append(" — ").append(runType);

        String env = resolveEnv();
        if (env != null) {
            sb.append(" | ").append(env);
        }

        sb.append(" | ").append(LocalDateTime.now().format(TIMESTAMP_FMT));
        return sb.toString();
    }

    /**
     * Builds an enriched description with runtime context.
     *
     * <p>Example output:
     * <pre>
     * Automated TestFly test execution
     *
     * Run type: API
     * Base URL: https://fakeapi.net
     * Environment: dev
     * Triggered by: hagul@MacBook-Pro
     * CI: Jenkins #42
     * Build URL: https://jenkins.example.com/job/demo/42
     * </pre>
     */
    public static String enrichDescription(String baseDescription, String runType, TestFlyConfig config) {
        StringBuilder sb = new StringBuilder();
        sb.append(baseDescription != null ? baseDescription : "Automated test execution powered by TestFly");
        sb.append("\n\n");

        sb.append("Run type: ").append(runType).append('\n');

        // Base URL — choose based on run type
        try {
            String webUrl = config.getExecution() != null
                    ? config.getExecution().getBaseUrl() : null;
            String apiUrl = config.getApi() != null
                    ? config.getApi().getBaseUrl() : null;

            if ("API".equals(runType)) {
                // API run → show api.baseUrl, fall back to execution.baseUrl
                if (apiUrl != null) {
                    sb.append("Base URL: ").append(apiUrl).append('\n');
                } else if (webUrl != null) {
                    sb.append("Base URL: ").append(webUrl).append('\n');
                }
            } else if ("Web".equals(runType)) {
                // Web run → show execution.baseUrl, fall back to api.baseUrl
                if (webUrl != null) {
                    sb.append("Base URL: ").append(webUrl).append('\n');
                } else if (apiUrl != null) {
                    sb.append("Base URL: ").append(apiUrl).append('\n');
                }
            } else {
                // Mixed or other → show both if different
                if (webUrl != null) {
                    sb.append("Web URL: ").append(webUrl).append('\n');
                }
                if (apiUrl != null && !apiUrl.equals(webUrl)) {
                    sb.append("API URL: ").append(apiUrl).append('\n');
                }
            }
        } catch (Exception ignored) {}

        // Environment
        String env = resolveEnv();
        if (env != null) {
            sb.append("Environment: ").append(env).append('\n');
        }

        // User + hostname
        String user     = System.getProperty("user.name", "unknown");
        String hostname = resolveHostname();
        sb.append("Triggered by: ").append(user);
        if (hostname != null) {
            sb.append('@').append(hostname);
        }
        sb.append('\n');

        // CI / Build info
        String buildNumber = System.getenv("BUILD_NUMBER");
        String buildUrl    = System.getenv("BUILD_URL");
        String ciName      = detectCiPlatform();
        if (ciName != null) {
            sb.append("CI: ").append(ciName);
            if (buildNumber != null) {
                sb.append(" #").append(buildNumber);
            }
            sb.append('\n');
        }
        if (buildUrl != null) {
            sb.append("Build URL: ").append(buildUrl).append('\n');
        }

        return sb.toString();
    }

    // ── Run type resolution ───────────────────────────────────────────────────

    /**
     * Resolves the effective run type from config setting and explicit override.
     *
     * @param configType   the value from {@code reporting.reportportal.type} (auto/api/web)
     * @param explicitType an explicit override from suite-level detection, or null
     * @return {@code "API"} or {@code "Web"}
     */
    public static String resolveRunType(String configType, String explicitType) {
        if (explicitType != null) return explicitType;
        if ("api".equalsIgnoreCase(configType)) return "API";
        if ("web".equalsIgnoreCase(configType)) return "Web";

        // auto — check system property first (set by SuiteExecutionListener),
        // then fall back to classpath heuristic
        String sysProp = System.getProperty("testfly.run.type");
        if ("API".equals(sysProp) || "Web".equals(sysProp)) return sysProp;

        return detectRunTypeFromClasspath();
    }

    /**
     * Auto-detects whether the test suite is API or Web by scanning the classpath
     * for base test classes. If {@code BaseApiTest} subclasses are found but no
     * {@code BaseTest} subclasses, returns "API". Otherwise returns "Web".
     */
    static String detectRunTypeFromClasspath() {
        try {
            ClassLoader cl = Thread.currentThread().getContextClassLoader();
            if (cl == null) cl = ReportPortalPropertiesWriter.class.getClassLoader();

            // Heuristic: try loading a known API-only test class
            // If BaseApiTest is on the classpath, check if it has subclasses
            // This is a best-effort heuristic — users can override via config or system property
            Class.forName("io.testfly.test.BaseApiTest", false, cl);
            // BaseApiTest exists on classpath — but we can't easily check if
            // test classes extend it without scanning. Default to "Web" unless
            // the system property is set.
        } catch (ClassNotFoundException e) {
            // BaseApiTest not on classpath — definitely Web
        }
        return "Web";
    }

    // ── Environment / CI detection ────────────────────────────────────────────

    private static String resolveEnv() {
        // 1. System property (set by -Denv=staging)
        String env = System.getProperty("env");
        if (env != null && !env.isBlank()) return env;

        // 2. Environment variable
        env = System.getenv("TESTFLY_ENV");
        if (env != null && !env.isBlank()) return env;

        // 3. CI environment hints
        if (System.getenv("GITHUB_ACTIONS") != null) return "github-actions";
        if (System.getenv("JENKINS_URL")    != null) return "jenkins";
        if (System.getenv("GITLAB_CI")      != null) return "gitlab";

        return null;
    }

    private static String resolveHostname() {
        try {
            return java.net.InetAddress.getLocalHost().getHostName();
        } catch (Exception e) {
            String hostname = System.getenv("HOSTNAME");
            return hostname;
        }
    }

    private static String detectCiPlatform() {
        if (System.getenv("GITHUB_ACTIONS")          != null) return "GitHub Actions";
        if (System.getenv("JENKINS_URL")             != null) return "Jenkins";
        if (System.getenv("GITLAB_CI")               != null) return "GitLab CI";
        if (System.getenv("CIRCLECI")                != null) return "CircleCI";
        if (System.getenv("TRAVIS")                  != null) return "Travis CI";
        if (System.getenv("BITBUCKET_BUILD_NUMBER")  != null) return "Bitbucket Pipelines";
        if (System.getenv("TF_BUILD")                != null) return "Azure Pipelines";
        return null;
    }

    // ── Utilities ─────────────────────────────────────────────────────────────

    private static void putIfNotBlank(Properties properties, String key, String value) {
        if (!isBlank(value)) {
            properties.setProperty(key, value);
        }
    }

    private static boolean isBlank(String value) {
        return value == null || value.trim().isEmpty();
    }

    private static String mask(String value) {
        if (value == null || value.length() <= 4) {
            return "****";
        }
        return "****" + value.substring(value.length() - 4);
    }
}
