package io.testfly.reporting.reportportal;

import io.testfly.config.DotEnvLoader;
import io.testfly.config.TestFlyConfig;

import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Properties;

/**
 * Converts {@code reporting.reportportal} YAML configuration into the
 * property format expected by the ReportPortal TestNG agent.
 *
 * <p>The agent reads either a {@code reportportal.properties} resource on the
 * classpath or system properties prefixed with {@code rp.}. This class supports
 * both mechanisms so TestFly can inject configuration at runtime without
 * requiring consumers to maintain a separate properties file.
 *
 * <p>ReportPortal property mapping:
 * <pre>
 * endpoint    → rp.endpoint
 * apiKey      → rp.api.key
 * project     → rp.project
 * launch      → rp.launch
 * description → rp.description
 * attributes  → rp.attributes
 * </pre>
 */
public final class ReportPortalPropertiesWriter {

    private static final String RP_ENDPOINT = "rp.endpoint";
    private static final String RP_API_KEY = "rp.api.key";
    private static final String RP_PROJECT = "rp.project";
    private static final String RP_LAUNCH = "rp.launch";
    private static final String RP_DESCRIPTION = "rp.description";
    private static final String RP_ATTRIBUTES = "rp.attributes";

    private ReportPortalPropertiesWriter() {
        // utility class
    }

    /**
     * Builds the ReportPortal properties from the supplied configuration.
     *
     * @param config the TestFly configuration; must not be {@code null}
     * @return a mutable {@link Properties} instance containing the ReportPortal keys
     * @throws IllegalArgumentException if the ReportPortal configuration is incomplete
     */
    public static Properties toProperties(TestFlyConfig config) {
        if (config == null) {
            throw new IllegalArgumentException("TestFlyConfig is required");
        }
        TestFlyConfig.Reporting reporting = config.getReporting();
        TestFlyConfig.Reporting.ReportPortal rp = reporting != null ? reporting.getReportPortal() : null;
        if (rp == null) {
            throw new IllegalArgumentException("reporting.reportportal configuration is required");
        }
        if (!rp.isEnabled()) {
            return new Properties();
        }

        validate(rp);

        Properties properties = new Properties();
        putIfNotBlank(properties, RP_ENDPOINT, DotEnvLoader.resolve(rp.getEndpoint()));
        putIfNotBlank(properties, RP_API_KEY, DotEnvLoader.resolve(rp.getApiKey()));
        putIfNotBlank(properties, RP_PROJECT, rp.getProject());
        putIfNotBlank(properties, RP_LAUNCH, rp.getLaunch());
        putIfNotBlank(properties, RP_DESCRIPTION, rp.getDescription());
        putIfNotBlank(properties, RP_ATTRIBUTES, rp.getAttributes());

        return properties;
    }

    /**
     * Writes the ReportPortal configuration as a properties file to the
     * requested path, then returns the absolute path of the generated file.
     *
     * <p>Consumers can place this file on the classpath (e.g. under
     * {@code target/classes}) before the ReportPortal agent initializes.
     *
     * @param config the TestFly configuration
     * @param target the destination file path
     * @return the written file path
     */
    public static Path writeToFile(TestFlyConfig config, Path target) {
        Properties properties = toProperties(config);
        try {
            Files.createDirectories(target.getParent());
            try (java.io.Writer writer = Files.newBufferedWriter(target)) {
                properties.store(writer, "Generated by TestFly for ReportPortal");
            }
            return target.toAbsolutePath();
        } catch (IOException e) {
            throw new UncheckedIOException("Failed to write ReportPortal properties to " + target, e);
        }
    }

    /**
     * Applies the ReportPortal configuration as system properties so the
     * ReportPortal agent can read them without a properties file.
     *
     * <p>Existing system properties are overwritten. This method is safe to
     * call before the TestNG listener starts.
     *
     * @param config the TestFly configuration
     */
    public static void applyAsSystemProperties(TestFlyConfig config) {
        Properties properties = toProperties(config);
        for (String name : properties.stringPropertyNames()) {
            System.setProperty(name, properties.getProperty(name));
        }
    }

    /**
     * Returns the properties content as a single string, suitable for tests or
     * debugging. Secrets are masked.
     */
    public static String toMaskedString(TestFlyConfig config) {
        Properties properties = toProperties(config);
        Properties masked = new Properties();
        for (String name : properties.stringPropertyNames()) {
            String value = properties.getProperty(name);
            if (name.toLowerCase(java.util.Locale.ROOT).contains("key")
                    || name.toLowerCase(java.util.Locale.ROOT).contains("token")) {
                value = mask(value);
            }
            masked.setProperty(name, value);
        }
        StringWriter writer = new StringWriter();
        try {
            masked.store(writer, "Generated by TestFly for ReportPortal");
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
        return writer.toString();
    }

    public static void validate(TestFlyConfig.Reporting.ReportPortal rp) {
        if (isBlank(rp.getEndpoint())) {
            throw new IllegalArgumentException("reporting.reportportal.endpoint is required when ReportPortal is enabled");
        }
        if (isBlank(rp.getApiKey())) {
            throw new IllegalArgumentException("reporting.reportportal.apiKey is required when ReportPortal is enabled");
        }
        if (isBlank(rp.getProject())) {
            throw new IllegalArgumentException("reporting.reportportal.project is required when ReportPortal is enabled");
        }
        if (isBlank(rp.getLaunch())) {
            throw new IllegalArgumentException("reporting.reportportal.launch is required when ReportPortal is enabled");
        }
    }

    private static void putIfNotBlank(Properties properties, String key, String value) {
        if (!isBlank(value)) {
            properties.setProperty(key, value);
        }
    }

    private static boolean isBlank(String value) {
        return value == null || value.trim().isEmpty();
    }

    private static String mask(String value) {
        if (value == null || value.length() <= 4) {
            return "****";
        }
        return "****" + value.substring(value.length() - 4);
    }
}
